name: Deploy Lambda to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Faz o checkout do código
      - name: Checkout Code
        uses: actions/checkout@v3

      # Configura o .NET Core
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0

      # Instala as dependências do projeto
      - name: Install Dependencies
        working-directory: ArithmeticCalculatorUserApi
        run: dotnet restore

      # Publica o projeto
      - name: Publish Project
        working-directory: ArithmeticCalculatorUserApi
        run: dotnet lambda package --configuration Release --output-package ../output/deployment.zip

      # Configura o AWS CLI
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Faz o deploy da Lambda
      - name: Deploy Lambda Function
        run: |
          aws lambda update-function-code \
            --function-name ArithmeticCalculatorUserApi \
            --zip-file fileb://./output/deployment.zip
