name: Deploy Lambda to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0

      - name: Install Lambda Tools
        run: dotnet tool install -g Amazon.Lambda.Tools

      - name: Add .NET tools to PATH
        run: echo "PATH=\$PATH:~/.dotnet/tools" >> $GITHUB_ENV

      - name: Install dependencies
        working-directory: ArithmeticCalculatorUserApi
        run: dotnet restore

      - name: Build the project
        working-directory: ArithmeticCalculatorUserApi
        run: dotnet lambda package -c Release -o package.zip

      - name: Install AWS CLI
        run: |
          wget "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -O "awscliv2.zip"
          unzip awscliv2.zip
          ./aws/install --update

      - name: Deploy to AWS Lambda
        working-directory: ArithmeticCalculatorUserApi
        run: |
          aws lambda update-function-code \
            --function-name ArithmeticCalculatorUserApi \
            --zip-file fileb://package.zip \
            --region ${{ secrets.AWS_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
